# Generated by Django 3.2.5 on 2021-07-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0004_auto_20210711_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
